services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: user-api-microservice
    environment:
      POSTGRES_DB: user-api-microservice
      POSTGRES_USER: ggg
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: