spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-api-microservice
    username: ggg
    password: pass

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# JWT Secret
api:
  security:
    token:
      secret: secret
